---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sop-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sop-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sop-assistant
  template:
    metadata:
      labels:
        app: sop-assistant
    spec:
      containers:
        - name: sop-assistant
          image: quay.io/vmogilev_rhmi/sop-assistant:latest
          ports:
            - containerPort: 8501
          env:
            - name: SOP_DIR
              value: "/sops"
          volumeMounts:
            - name: sop-volume
              mountPath: /sops
      volumes:
        - name: sop-volume
          persistentVolumeClaim:
            claimName: sop-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sop-assistant
spec:
  selector:
    app: sop-assistant
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: sop-assistant
spec:
  to:
    kind: Service
    name: sop-assistant
  port:
    targetPort: 8501
  tls:
    termination: edge
